ktor:
    application:
        modules:
            - com.mapprjct.ApplicationKt.module
    deployment:
        port: 8080
postgres:
  url: "jdbc:postgresql://localhost:5432/geomap"
  user: postgres
  password: kilopkil12
jwt:
  secret: "f38a4a6da1a0fce3a50e0ef2335ac8ad51c39"
  issuer: "map.server"
  audience: "jwt-audience"
  realm: "app"
